# ==============================
# Gemini Image Generator Project
# ==============================

# Design Pattern (Singleton)
class Singleton:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance


# Base Class
class ImageGenerator(Singleton):

    def generate(self, prompt):
        return "Generating image..."


# Inheritance & Overriding
class Gemini(ImageGenerator):

    def generate(self, prompt):
        return f"Image '{prompt}' has been successfully generated by Gemini."


# Main Program
def main():
    try:
        print("===== Gemini Image Generator =====")

        prompt = input("Enter your image prompt: ")

        if prompt.strip() == "":
            raise ValueError("Prompt cannot be empty.")

        gemini = Gemini()

        result = gemini.generate(prompt)

        print("\nResult:")
        print(result)

    except ValueError as e:
        print("Error:", e)

    except Exception as e:
        print("Unknown Error:", e)


# Unit Test / Test Case
def test_generate():

    gemini = Gemini()

    expected = "Image 'Cat' has been successfully generated by Gemini."

    assert gemini.generate("Cat") == expected


# Run Program
if __name__ == "__main__":
    main()